# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a_7TcFFgT2k5SIGlxdu2lOE1OaaTw_u4
"""
from datetime import datetime

#文件封装了"旅行规划智能体"所需的七个 Prompt 模板
#模块总览:
#       1 Intent Parsing Prompt (/parse_intent)
#       2 Date Normalization Prompt (/normalize_date)
#       3 Clarify Prompt (/clarify)
#       4 Query Rewrite Prompt (/query_rewrite)
#       5 Assemble Context Prompt (/assemble_context)
#       6 Plan Actions Prompt (/plan_actions)
#       7 Aggregate Prompt (/aggregate)

# ----------------------------------------------------------
# 1 Intent Parsing Prompt
# ----------------------------------------------------------

def prompt_parse_intent(user_input: str, conversation_history: list = None) -> str:
    """
    功能: 解析用户输入，提取任务类型与旅行意图槽位信息
    输出字段:
        task_type: 任务类型（itinerary / recommendation ）
        subtype: 若为推荐类，则细分为 "hotel"（酒店） / "food"（餐厅） / "attraction"（景点/活动
        origin: 出发地
        dest_pref: 目的地列表
        date_window: 出行日期范围
        trip_len_days: 行程天数
        budget_total_cny: 预算
        party: 出行人数（成人/儿童）
        tags: 标签
        must_haves: 必备条件
        missing_slots: 缺失字段
        confidence: 置信度
    
    参数:
        conversation_history: 历史对话列表，格式为 [{"user": "用户输入", "response": {...}}, ...]
    """
    history_context = ""
    previous_task_type = None
    if conversation_history and len(conversation_history) > 0:
        history_context = "\n\n## 历史对话上下文（请参考之前的对话信息）：\n"
        for idx, turn in enumerate(conversation_history[-3:], 1):  # 只取最近3轮对话
            user_msg = turn.get("user", "")
            response = turn.get("response", {})
            intent = response.get("intent_parsed", {})
            
            # 提取 task_type（重要：用于继承任务类型）
            task_type = intent.get("task_type")
            if task_type and task_type != "other":
                previous_task_type = task_type
            
            # 提取关键信息
            key_info = []
            if task_type:
                key_info.append(f"任务类型: {task_type}")
            if intent.get("dest_pref"):
                key_info.append(f"目的地: {', '.join(intent.get('dest_pref', []))}")
            if intent.get("origin"):
                key_info.append(f"出发地: {intent.get('origin')}")
            if intent.get("date_window", {}).get("from"):
                key_info.append(f"日期: {intent.get('date_window', {}).get('from')}")
            if intent.get("trip_len_days"):
                key_info.append(f"天数: {intent.get('trip_len_days')}天")
            if intent.get("budget_total_cny"):
                key_info.append(f"预算: {intent.get('budget_total_cny')}元")
            
            history_context += f"第{idx}轮:\n"
            history_context += f"  用户: {user_msg}\n"
            if key_info:
                history_context += f"  已确认信息: {', '.join(key_info)}\n"
            history_context += "\n"
    
    # 如果有历史任务类型，在 prompt 中强调继承
    task_type_instruction = ""
    if previous_task_type:
        task_type_instruction = f"\n⚠️ 重要提示：历史对话中的任务类型是 \"{previous_task_type}\"，当前输入应该继承这个任务类型（除非用户明确改变任务类型）。"
    
    return f"""
你是一名智能旅行规划助手。
请阅读以下用户输入，判断任务类型并提取完整的旅行意图槽位，以 JSON 格式输出。

任务类型规则：
- 若用户想要生成具体行程（包含天数、日期、预算等），则 task_type = "itinerary"
- 若用户只想推荐景点、美食、酒店等内容，则 task_type = "recommendation"
- 若不属于以上两类，则 task_type = "other"

严格要求：
1) 不得臆造未出现的信息；
2) 未提供的字段要加入 missing_slots；
3) 出发地、目的地、日期、天数、预算、人数若缺失必须标出；
4) 如果历史对话中已有相关信息，请优先使用历史信息，当前输入只补充或更新缺失的部分；
5) **如果历史对话中已有 task_type，必须继承该 task_type（除非用户明确改变任务类型）**；
6) 只返回 JSON。
{history_context}{task_type_instruction}
当前用户输入: "{user_input}"

输出示例（仅作格式参考）:
{{
  "task_type": "recommendation",
  "origin": null,
  "dest_pref": ["巴黎"],
  "date_window": {{"from": null, "to": null}},
  "trip_len_days": null,
  "budget_total_cny": null,
  "party": {{"adults": null, "children": null}},
  "tags": ["艺术", "博物馆"],
  "must_haves": [],
  "missing_slots": ["date_window", "budget_total_cny"],
  "confidence": 0.9
}}

请只返回 JSON 格式输出。
    """

# ----------------------------------------------------------
# 2 Date Normalization Prompt
# ----------------------------------------------------------

def prompt_normalize_date(user_input: str, today: str = None) -> str:
    """
    功能: 将模糊日期描述（如"国庆""下个月初"）转换为具体时间段。
    """
    if today is None:
        today = datetime.now().strftime("%Y-%m-%d")
    return f"""
你是一名时间解析助手。
请将输入中的模糊日期（如“国庆”“下个月”）转换为具体日期范围。

当前日期: {today}
输入: "{user_input}"
如果未提到具体出发日期，请推理一个合理的未来日期（例如：从今日起10天后出发）。
输出示例:
{{
  "from": "2025-10-01",
  "to": "2025-10-07",
  "uncertainty": false,
  "reason": "国庆假期7天"
}}

请仅输出 JSON。
    """

# ----------------------------------------------------------
# 3 Clarify Prompt
# ----------------------------------------------------------

def prompt_clarify(missing_slots: list, known_info: dict = None) -> str:
    """
    功能: 根据缺失槽位生成追问语句，用于引导用户补充信息。
    """
    return f"""
你是一名旅行顾问。
请根据缺失的信息槽位，生成简短、自然的追问语句，引导用户补充关键信息。

已知信息: {known_info or {}}
缺失槽位: {missing_slots}

输出格式:
{{
  "questions": ["请问您从哪里出发？", "您的预算大概是多少？"],
  "suggestions": ["示例: 我打算从上海出发，预算8000元左右。"]
}}

请只返回 JSON。
    """

def prompt_clarify1(missing_slots: list, known_info: dict = None) -> str:
    """
    功能: 根据缺失槽位生成自然追问，引导用户补充关键信息。
    """
    return f"""
你是一名友好的旅行顾问。
请根据缺失的字段生成简短、自然的追问语句，帮助用户补充完整信息。

已知信息: {known_info or {}}
缺失槽位: {missing_slots}

返回 JSON 格式:
{{
  "questions": ["请问您的出发地是哪里？", "打算玩几天？", "预算大概是多少？"],
  "suggestions": ["示例：我从北京出发，打算去巴黎玩5天，预算一万元。"]
}}

要求：
- 问句应自然简短；
- 一般生成 2~3 个核心追问；
- 示例回答需完整涵盖缺失字段；
- 只返回 JSON。
    """


# ----------------------------------------------------------
# 4 Query Rewrite Prompt
# ----------------------------------------------------------

def prompt_query_rewrite(user_input: str, slots: dict = None) -> str:
    """
    功能: 将模糊自然语言问题改写为结构化检索 Query，便于 RAG 调用。
    """
    return f"""
你是一名检索优化助手。
请将用户的自然语言输入改写为结构化查询关键词，以便进行向量数据库检索。


输入: "{user_input}"
已识别槽位: {slots or {}}

输出格式（示例取值仅供参考，不得照抄）:
{{
  "keywords": ["巴黎", "十月", "天气", "签证"],
  "city_alias": ["Paris"],
  "time_window": {{"from": "2025-10-01", "to": "2025-10-31"}},
  "tags": ["climate", "visa"]
}}

请只输出 JSON。
    """

# ----------------------------------------------------------
# 5 Assemble Context Prompt
# ----------------------------------------------------------

def prompt_assemble_context(question: str, chunk_titles: list) -> str:
    """
    功能: 汇总 RAG 检索结果的文档要点，生成摘要。
    """
    return f"""
你是一名信息整合助手。
请阅读以下与问题相关的文档标题，并生成简洁摘要与重点。

问题: "{question}"
相关文档: {chunk_titles}

输出格式:
{{
  "summary": "巴黎十月气温10~17℃，多雨但适合出行。",
  "highlights": ["气温10~17℃", "游客较少"],
  "sources": [{{"id": "1", "title": "巴黎天气", "url": "https://example.com"}}]
}}

请只返回 JSON。
    """

# ----------------------------------------------------------
# 6 Plan Actions Prompt
# ----------------------------------------------------------

def prompt_plan_actions(slots: dict) -> str:
    """
    功能: 将槽位信息转换为系统可执行的行动计划。
    """
    return f"""
你是一名旅行自动化规划助手。
请根据用户的槽位信息生成一组可执行的行动步骤，每个步骤包含 action / target / value 字段。

槽位信息: {slots}

输出格式:
{{
  "steps": [
    {{"action": "set_origin", "value": "上海"}},
    {{"action": "set_destination", "value": "巴黎"}},
    {{"action": "set_dates", "from": "2025-10-01", "to": "2025-10-07"}},
    {{"action": "set_budget", "value": 10000}},
    {{"action": "search"}}
  ],
  "assumptions": ["多目的地取第一个"],
  "notes": ["用户偏好为直飞航班"]
}}

请只输出 JSON。
    """

# ----------------------------------------------------------
# 7 Aggregate Prompt
# ----------------------------------------------------------

def prompt_aggregate(candidates: list, user_prefs: dict = None) -> str:
    """
    功能: 比较多个候选旅行方案，输出最优推荐。
    """
    return f"""
你是一名旅行方案评估助手。
请对比多个候选方案，根据价格、时长、舒适度、用户偏好等因素进行综合分析，并输出推荐结果。

候选方案: {candidates}
用户偏好: {user_prefs or {}}

输出格式:
{{
  "plans": [
    {{
      "id": "A",
      "summary": "直飞，早去晚回",
      "pros": ["省时"],
      "cons": ["略贵"],
      "total_price": 6800
    }},
    {{
      "id": "B",
      "summary": "转机一次，价格更低",
      "pros": ["更便宜"],
      "cons": ["需中转"],
      "total_price": 5200
    }}
  ],
  "recommendation": "推荐方案A（直飞更便捷）"
}}

请只输出 JSON。
    """